### ISSUE TITLE
Issue while importing a solution which contains PowerApps: CanvasApp import: FAILURE: One or more errors occurred

### ISSUE THREAD

**Issue by rohannevrikar** [microsoft/PowerApps-Samples#106]
I'm using [WorkwithSolutions](https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/C%23/WorkwithSolutions) sample to import/export solutions. If I'm authenticating CrmServiceClient using username and password (AuthType=O365), then everything is working as expected. But if I'm using ClientID and ClientSecret (AuthType=ClientSecret), then an exception is thrown when the solution contains a PowerApp with the following errors: 

 Message: CanvasApp import: FAILURE: One or more errors occurred.
 Message: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph

 `serviceClient.Execute(impSolReq); //This line throws the exception`

I'm using application user which I created on Dynamics 365. That application user's app ID is clientID of an AD app which I created. I have assigned System Customizer role to the application user. 
The ID which is being shown in the error message is that of Azure AD Object ID property of the application user. 

Note: I'm able to import/export a solution if it contains flow. I'm able to only export a solution if it contains a PowerApp, but not able to import the solution. I've tried on both managed and unmanaged solutions, not working on both the types. 

Is this a bug, or am I missing anything here? 

Here is the stack trace:

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : ************ FaultException`1 - ImportSolution : Execute (ImportSolution) request to CRM from IOrganizationService |=> CanvasApp import: FAILURE: One or more errors occurred.
Source  : mscorlib
Method  : HandleReturnMessage
Date    : 01-04-2020
Time    : 12:06:21
Error   : Message: CanvasApp import: FAILURE: One or more errors occurred.
ErrorCode: -2147188704
Trace:
Error Details   :
ApiExceptionSourceKey   : Plugin/Microsoft.Crm.WebServices.ImportXmlService
ApiOriginalExceptionKey : Microsoft.Crm.Tools.ImportExportPublish.ImportGenericEntitiesException: CanvasApp import: FAILURE: One or more errors occurred. ---> Microsoft.Crm.Tools.ImportExportPublish.ImportGenericEntitiesException: CanvasApp import: FAILURE: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportHandler.ImportInternal()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.ImportAndUpdateProgress(ImportHandler ih)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.ProcessHandlers(String[] ImportEntities, Hashtable ht, String& curPath, ImportHandler& ihForCurrentPath, CounterList listCounters)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.RunImport(String[] ImportEntities)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImport(String[] ImportEntities)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImport()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImportInternal(Boolean withSolutionManifest)
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.WebServices.ImportXmlService.ImportSolutionSkipCapableInternal(Boolean overwriteUnmanagedCustomizations, Boolean publishWorkflows, Byte[] customizationFile, Guid importJobId, Boolean convertToManaged, Boolean skipProductUpdateDependencies, Boolean holdingSolution, ExecutionContext context, Boolean skipRibbonMetadataProcessing, LayerDesiredOrder layerDesiredOrder)
   at Microsoft.Crm.WebServices.ImportXmlService.ImportSolutionSkipCapable(Boolean overwriteUnmanagedCustomizations, Boolean publishWorkflows, Byte[] customizationFile, Guid importJobId, Boolean convertToManaged, Boolean skipProductUpdateDependencies, Boolean holdingSolution, ExecutionContext context, Boolean skipRibbonMetadataProcessing, LayerDesiredOrder layerDesiredOrder)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.<>c__DisplayClass3_0.<RunStep>b__0()
ApiStepKey      : 1b830950-e106-4ee1-b3fd-d348cb65dc8d
ApiDepthKey     : 1
ApiActivityIdKey        : db6f2820-6979-4279-80c3-ef4e9bea4458
ApiPluginSolutionNameKey        : System
ApiStepSolutionNameKey  : System
ApiExceptionCategory    : SystemFailure
ApiExceptionMesageName  : ImportGenericEntitiesError
ApiExceptionHttpStatusCode      : 500
0       : System.AggregateException: One or more errors occurred. ---> Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
---> (Inner Exception #0) Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()<---

HasRetried      : True
RetryExecutionStatus    : Microsoft.Crm.Core.Extensions.Retry.RetryExecutionStatus

Stack Trace     : Server stack trace:
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.<>c__DisplayClass40_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================
Inner Exception Level 1 :
==OrganizationServiceFault Info=======================================================================================
Error   : Message: CanvasApp import: FAILURE: One or more errors occurred.
ErrorCode: -2147188704
Trace:
Time    : 01-04-2020 06:36:20
ErrorCode       : -2147188704
Date    : 01-04-2020
Time    : 12:06:21
Trace   : Not Provided
======================================================================================================================
Inner Exception Level 2 :
==OrganizationServiceFault Info=======================================================================================
Error   : Message: System.AggregateException: One or more errors occurred. ---> Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
---> (Inner Exception #0) Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()<---
: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #6568AD27
ErrorCode: -2147220970
Trace:
Time    : 01-04-2020 06:36:20
ErrorCode       : -2147220970
Date    : 01-04-2020
Time    : 12:06:21
Trace   : Not Provided
======================================================================================================================
Inner Exception Level 3 :
==OrganizationServiceFault Info=======================================================================================
Error   : Message: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
ErrorCode: -2147015854
Trace:
Time    : 01-04-2020 06:36:20
ErrorCode       : -2147015854
Date    : 01-04-2020
Time    : 12:06:21
Trace   : Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : [TerminalFailure] Failed to Execute Command - ImportSolution : RequestID=bd4c7fd2-3ca5-4e0d-bc86-7e4198ac7cac : Execute (ImportSolution) request to CRM from IOrganizationService duration=00:00:06.8563372 ExceptionMessage = CanvasApp import: FAILURE: One or more errors occurred.
Source  : mscorlib
Method  : HandleReturnMessage
Date    : 01-04-2020
Time    : 12:06:21
Error   : Message: CanvasApp import: FAILURE: One or more errors occurred.
ErrorCode: -2147188704
Trace:
Error Details   :
ApiExceptionSourceKey   : Plugin/Microsoft.Crm.WebServices.ImportXmlService
ApiOriginalExceptionKey : Microsoft.Crm.Tools.ImportExportPublish.ImportGenericEntitiesException: CanvasApp import: FAILURE: One or more errors occurred. ---> Microsoft.Crm.Tools.ImportExportPublish.ImportGenericEntitiesException: CanvasApp import: FAILURE: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportHandler.ImportInternal()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.ImportAndUpdateProgress(ImportHandler ih)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.ProcessHandlers(String[] ImportEntities, Hashtable ht, String& curPath, ImportHandler& ihForCurrentPath, CounterList listCounters)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.RunImport(String[] ImportEntities)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImport(String[] ImportEntities)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImport()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImportInternal(Boolean withSolutionManifest)
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.WebServices.ImportXmlService.ImportSolutionSkipCapableInternal(Boolean overwriteUnmanagedCustomizations, Boolean publishWorkflows, Byte[] customizationFile, Guid importJobId, Boolean convertToManaged, Boolean skipProductUpdateDependencies, Boolean holdingSolution, ExecutionContext context, Boolean skipRibbonMetadataProcessing, LayerDesiredOrder layerDesiredOrder)
   at Microsoft.Crm.WebServices.ImportXmlService.ImportSolutionSkipCapable(Boolean overwriteUnmanagedCustomizations, Boolean publishWorkflows, Byte[] customizationFile, Guid importJobId, Boolean convertToManaged, Boolean skipProductUpdateDependencies, Boolean holdingSolution, ExecutionContext context, Boolean skipRibbonMetadataProcessing, LayerDesiredOrder layerDesiredOrder)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.<>c__DisplayClass3_0.<RunStep>b__0()
ApiStepKey      : 1b830950-e106-4ee1-b3fd-d348cb65dc8d
ApiDepthKey     : 1
ApiActivityIdKey        : db6f2820-6979-4279-80c3-ef4e9bea4458
ApiPluginSolutionNameKey        : System
ApiStepSolutionNameKey  : System
ApiExceptionCategory    : SystemFailure
ApiExceptionMesageName  : ImportGenericEntitiesError
ApiExceptionHttpStatusCode      : 500
0       : System.AggregateException: One or more errors occurred. ---> Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
---> (Inner Exception #0) Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()<---

HasRetried      : True
RetryExecutionStatus    : Microsoft.Crm.Core.Extensions.Retry.RetryExecutionStatus

Stack Trace     : Server stack trace:
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.<>c__DisplayClass40_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================
Inner Exception Level 1 :
==OrganizationServiceFault Info=======================================================================================
Error   : Message: CanvasApp import: FAILURE: One or more errors occurred.
ErrorCode: -2147188704
Trace:
Time    : 01-04-2020 06:36:20
ErrorCode       : -2147188704
Date    : 01-04-2020
Time    : 12:06:21
Trace   : Not Provided
======================================================================================================================
Inner Exception Level 2 :
==OrganizationServiceFault Info=======================================================================================
Error   : Message: System.AggregateException: One or more errors occurred. ---> Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
---> (Inner Exception #0) Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
   at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()<---
: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #6568AD27
ErrorCode: -2147220970
Trace:
Time    : 01-04-2020 06:36:20
ErrorCode       : -2147220970
Date    : 01-04-2020
Time    : 12:06:21
Trace   : Not Provided
======================================================================================================================
Inner Exception Level 3 :
==OrganizationServiceFault Info=======================================================================================
Error   : Message: Code: GraphUserDetailNotFound Message: The user '385bc191-1bf9-45ec-8dca-ca541c3e7796' was not found in Graph. Client Request Id: .
ErrorCode: -2147015854
Trace:
Time    : 01-04-2020 06:36:20
ErrorCode       : -2147015854
Date    : 01-04-2020
Time    : 12:06:21
Trace   : Not Provided
======================================================================================================================

**Comment by rohannevrikar** [comment]
Got in touch with Microsoft's support team regarding this. This feature is not supported yet because of some technical blockage. I have dropped a feature ask for the same in the community:
https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Support-AuthType-ClientSecret-for-PowerApps-in-Dynamics-SDK/idi-p/531701#M30321
