### ISSUE TITLE
PowerApps Import Solution: "Connector import: FAILURE: One or more errors occurred"

### ISSUE THREAD

**Issue by luismachaner** [microsoft/PowerApps-Samples#120]
Our solution contains:

- Canvas PowerApp
- Power Automate Flow
- Custom Connector

The app uses: a) the connector to populate dropdowns and b) the flow to perform some logic. In turn, the flow uses the same custom connector, plus two standard connectors, as part of its logic.

Following this [Microsoft Hands-on-lab](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tutorial-faq), we are able to get through all the steps (but the last one):

- We have created the Pipeline that exports the solution from DEV environment and commits it to the source repo. It runs OK
- We have created the Pipeline that imports the unmanaged solution to a build (BLD) environment and exports it as managed solution, generating an artifact. (Note: we added a "PowerApps Publish Customizations" task that we noticed is missing in the documentation, but we got the same error in the final step). It runs OK
- We have created the Release pipeline to deploy the managed solution to the target environment (TST), but it runs NOK. We get the error referred above (log pasted below). 

Additional comments: 

- PowerApps BuildTools version: **0.1.16**
- We are able to manually import the generated artifact into the target environment, with no errors.
- If we import the solution manually, the Release pipeline runs OK. So we have a workaround, but it is still an issue.
- If we just remove the custom connector from the solution (keeping all dependencies from the other solution components) the error is the same. When removing the dependencies, then Release pipeline runs OK. But we need the connector.
- We opened an issue to Power Platform support. A Microsoft support engineer helped us analyzing the scenario and then he told us to open an issue here, as it seems to be specifically related to the tools.

PowerApps Import solution task log:
```
Unhandled exception: 
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: Connector import: FAILURE: One or more errors occurred.Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>80a5a626-7309-4dd5-b9b6-96aa4ee28775</ActivityId>
  <ErrorCode>-2147188704</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionSourceKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Plugin/Microsoft.Crm.WebServices.ImportXmlService</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiOriginalExceptionKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Microsoft.Crm.Tools.ImportExportPublish.ImportGenericEntitiesException: Connector import: FAILURE: One or more errors occurred. ---&gt; Microsoft.Crm.Tools.ImportExportPublish.ImportGenericEntitiesException: Connector import: FAILURE: One or more errors occurred. ---&gt; System.AggregateException: One or more errors occurred. ---&gt; System.InvalidOperationException: The API call failed with http status code 'InternalServerError' and response content '{"error":{"code":"InternalServerError","message":"Encountered internal server error. The tracking Id is '6cd80ea9-c99a-4689-bd9b-793c06bba79e'."}}'
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;&gt;c__DisplayClass61_0`2.&lt;&lt;CallPowerAppsEndpoint&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;CallPowerAppsEndpoint&gt;d__61`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ConnectorService.&lt;ImportConnectorSolutionDefinition&gt;d__79.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.ObjectModel.ConnectorService.Create(IBusinessEntity entity, ExecutionContext context)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportEntityHandlerBase.&lt;&gt;c__DisplayClass3_0.&lt;EnsureEntityExisted&gt;b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportConnectorHandler.ImportItem()
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Tools.ImportExportPublish.ImportConnectorHandler.ImportItem()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportHandler.ImportInternal()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.ImportAndUpdateProgress(ImportHandler ih)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.ProcessHandlers(String[] ImportEntities, Hashtable ht, String&amp; curPath, ImportHandler&amp; ihForCurrentPath, CounterList listCounters)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.RunImport(String[] ImportEntities)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImport(String[] ImportEntities)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImport()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImportInternal(Boolean withSolutionManifest)
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.WebServices.ImportXmlService.ImportSolutionSkipCapableInternal(Boolean overwriteUnmanagedCustomizations, Boolean publishWorkflows, Byte[] customizationFile, Guid importJobId, Boolean convertToManaged, Boolean skipProductUpdateDependencies, Boolean holdingSolution, ExecutionContext context, Boolean skipQueueRibbonJob, LayerDesiredOrder layerDesiredOrder, Boolean asyncRibbonProcessing, EntityCollection componentParameters)
   at Microsoft.Crm.WebServices.ImportXmlService.ImportSolutionSkipCapable(Boolean overwriteUnmanagedCustomizations, Boolean publishWorkflows, Byte[] customizationFile, Guid importJobId, Boolean convertToManaged, Boolean skipProductUpdateDependencies, Boolean holdingSolution, ExecutionContext context, Boolean skipQueueRibbonJob, LayerDesiredOrder layerDesiredOrder, Boolean asyncRibbonProcessing, EntityCollection componentParameters)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.&lt;&gt;c__DisplayClass3_0.&lt;RunStep&gt;b__0()</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiStepKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/" i:type="d4p1:guid">1b830950-e106-4ee1-b3fd-d348cb65dc8d</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiDepthKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">2</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiActivityIdKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/" i:type="d4p1:guid">80a5a626-7309-4dd5-b9b6-96aa4ee28775</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiPluginSolutionNameKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">System</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiStepSolutionNameKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">System</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionCategory</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">SystemFailure</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionMesageName</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">ImportGenericEntitiesError</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionHttpStatusCode</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">500</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>0</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">System.AggregateException: One or more errors occurred. ---&gt; System.InvalidOperationException: The API call failed with http status code 'InternalServerError' and response content '{"error":{"code":"InternalServerError","message":"Encountered internal server error. The tracking Id is '6cd80ea9-c99a-4689-bd9b-793c06bba79e'."}}'
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;&gt;c__DisplayClass61_0`2.&lt;&lt;CallPowerAppsEndpoint&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;CallPowerAppsEndpoint&gt;d__61`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ConnectorService.&lt;ImportConnectorSolutionDefinition&gt;d__79.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.ObjectModel.ConnectorService.Create(IBusinessEntity entity, ExecutionContext context)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportEntityHandlerBase.&lt;&gt;c__DisplayClass3_0.&lt;EnsureEntityExisted&gt;b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportConnectorHandler.ImportItem()
---&gt; (Inner Exception #0) System.InvalidOperationException: The API call failed with http status code 'InternalServerError' and response content '{"error":{"code":"InternalServerError","message":"Encountered internal server error. The tracking Id is '6cd80ea9-c99a-4689-bd9b-793c06bba79e'."}}'
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;&gt;c__DisplayClass61_0`2.&lt;&lt;CallPowerAppsEndpoint&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;CallPowerAppsEndpoint&gt;d__61`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ConnectorService.&lt;ImportConnectorSolutionDefinition&gt;d__79.MoveNext()&lt;---
</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>HasRetried</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">True</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>RetryExecutionStatus</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Microsoft.Crm.Core.Extensions.Retry.RetryExecutionStatus</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <HelpLink>http://go.microsoft.com/fwlink/?LinkID=398563&amp;error=Microsoft.Crm.CrmException%3a80048020&amp;client=platform</HelpLink>
  <Message>Connector import: FAILURE: One or more errors occurred.</Message>
  <Timestamp>2020-05-21T11:58:11.2424764Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>80a5a626-7309-4dd5-b9b6-96aa4ee28775</ActivityId>
    <ErrorCode>-2147188704</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <HelpLink i:nil="true" />
    <Message>Connector import: FAILURE: One or more errors occurred.</Message>
    <Timestamp>2020-05-21T11:58:11.2424764Z</Timestamp>
    <ExceptionRetriable>false</ExceptionRetriable>
    <ExceptionSource i:nil="true" />
    <InnerFault>
      <ActivityId>80a5a626-7309-4dd5-b9b6-96aa4ee28775</ActivityId>
      <ErrorCode>-2147220970</ErrorCode>
      <ErrorDetails xmlns:d4p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
      <HelpLink i:nil="true" />
      <Message>System.AggregateException: One or more errors occurred. ---&gt; System.InvalidOperationException: The API call failed with http status code 'InternalServerError' and response content '{"error":{"code":"InternalServerError","message":"Encountered internal server error. The tracking Id is '6cd80ea9-c99a-4689-bd9b-793c06bba79e'."}}'
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;&gt;c__DisplayClass61_0`2.&lt;&lt;CallPowerAppsEndpoint&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;CallPowerAppsEndpoint&gt;d__61`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ConnectorService.&lt;ImportConnectorSolutionDefinition&gt;d__79.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Crm.ObjectModel.ConnectorService.Create(IBusinessEntity entity, ExecutionContext context)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportEntityHandlerBase.&lt;&gt;c__DisplayClass3_0.&lt;EnsureEntityExisted&gt;b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportConnectorHandler.ImportItem()
---&gt; (Inner Exception #0) System.InvalidOperationException: The API call failed with http status code 'InternalServerError' and response content '{"error":{"code":"InternalServerError","message":"Encountered internal server error. The tracking Id is '6cd80ea9-c99a-4689-bd9b-793c06bba79e'."}}'
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;&gt;c__DisplayClass61_0`2.&lt;&lt;CallPowerAppsEndpoint&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;CallPowerAppsEndpoint&gt;d__61`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ConnectorService.&lt;ImportConnectorSolutionDefinition&gt;d__79.MoveNext()&lt;---
: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #5CFFE689</Message>
      <Timestamp>2020-05-21T11:58:11.2424764Z</Timestamp>
      <ExceptionRetriable>false</ExceptionRetriable>
      <ExceptionSource i:nil="true" />
      <InnerFault>
        <ActivityId>80a5a626-7309-4dd5-b9b6-96aa4ee28775</ActivityId>
        <ErrorCode>-2147220970</ErrorCode>
        <ErrorDetails xmlns:d5p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
        <HelpLink i:nil="true" />
        <Message>System.InvalidOperationException: The API call failed with http status code 'InternalServerError' and response content '{"error":{"code":"InternalServerError","message":"Encountered internal server error. The tracking Id is '6cd80ea9-c99a-4689-bd9b-793c06bba79e'."}}'
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;&gt;c__DisplayClass61_0`2.&lt;&lt;CallPowerAppsEndpoint&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.ObjectModel.ResourceStack.AsyncRetry.&lt;Retry&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;CallPowerAppsEndpoint&gt;d__61`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.ObjectModel.ConnectorService.&lt;ImportConnectorSolutionDefinition&gt;d__79.MoveNext(): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #4A9689D2</Message>
        <Timestamp>2020-05-21T11:58:11.2424764Z</Timestamp>
        <ExceptionRetriable>false</ExceptionRetriable>
        <ExceptionSource i:nil="true" />
        <InnerFault i:nil="true" />
        <OriginalException i:nil="true" />
        <TraceText i:nil="true" />
      </InnerFault>
      <OriginalException i:nil="true" />
      <TraceText i:nil="true" />
    </InnerFault>
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>
1 more errors. Click on expand view in the context menu to view complete logs.
```

**Comment by luismachaner** [comment]
Any feedback, please?
