### ISSUE TITLE
PowerAppToolInstaller error on agent

### ISSUE THREAD

**Issue by JeroenDaniels** [microsoft/PowerApps-Samples#123]
I try to use the PowerApps BuildTools but keep getting the following error at the first PowerAppsToolInstaller step:  

Installing PS module Microsoft.Xrm.OnlineManagementAPI - 1.2.0.1 ... ##[error]Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."  

The error occurs on our own Build Agents but work at the Azure Hosted VS2017 Agents. Are there some kind of requirements the Agent has to adhere to?

**Comment by JeroenDaniels** [comment]
I added a "NuGet install" step to the pipeline and get a new exception now:

2020-06-02T10:42:29.8896652Z 
2020-06-02T10:42:29.8925317Z Name                           Version          Source           Summary                                               
2020-06-02T10:42:29.8942855Z ----                           -------          ------           -------                                               
2020-06-02T10:42:29.8968235Z nuget                          2.8.5.208        https://onege... NuGet provider for the OneGet meta-package manager    
2020-06-02T10:42:30.1910876Z ##[debug]Using the provider 'PowerShellGet' for searching packages.
2020-06-02T10:42:30.1961276Z ##[debug]00:00:03.5658078 PackageProvider::FindPackage with name NuGet
2020-06-02T10:42:30.2020345Z ##[debug]00:00:03.5665594 Calling SearchForPackages After Select 1
2020-06-02T10:42:30.2069813Z ##[debug]00:00:03.5884121 Calling New() : MethodName = 'FindPackage'
2020-06-02T10:42:30.2118234Z ##[debug]00:00:03.5884892 Name: NuGet
2020-06-02T10:42:30.2166084Z ##[debug]00:00:03.5903764 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
2020-06-02T10:42:30.2216304Z ##[debug]00:00:03.7937959 In PowerShellGet Provider - 'Find-Package'.
2020-06-02T10:42:30.2273458Z ##[debug]00:00:03.9532962 OPTION: Name => NuGet
2020-06-02T10:42:30.2328845Z ##[debug]The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
2020-06-02T10:42:30.2377433Z ##[debug]Getting the provider object for the PackageManagement Provider 'NuGet'.
2020-06-02T10:42:30.2431303Z ##[debug]The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
2020-06-02T10:42:30.2479720Z ##[debug]00:00:04.1943233 PackageProvider::FindPackage with name NuGet
2020-06-02T10:42:30.2529058Z ##[debug]00:00:04.3064442 Calling 'NuGet'::'FindPackage' - name='NuGet', requiredVersion='',minimumVersion='', maximumVersion='''.
2020-06-02T10:42:30.2597394Z ##[debug]00:00:04.3070397 Iterating 'NuGet'.
2020-06-02T10:42:30.2654655Z ##[debug]00:00:04.3257491 Calling 'NuGetRequest'::'RegisteredPackageSources', 'C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\NuGet\nuget.config'.
2020-06-02T10:42:30.2876139Z ##[debug]00:00:04.3264300 Loading a configuration from file 'C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\NuGet\nuget.config'.
2020-06-02T10:42:30.2978734Z ##[debug]00:00:04.3271127 Loaded a configuration from file 'C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\NuGet\nuget.config'.
2020-06-02T10:42:30.2983139Z ##[debug]00:00:04.3285225 There are '1' registered sources in 'NuGet' provider.
2020-06-02T10:42:30.3034082Z ##[debug]00:00:04.3300858 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered sources in 'NuGet' provider.
2020-06-02T10:42:30.4618470Z ##[debug]00:00:05.6526960 Source 'https://www.powershellgallery.com/api/v2' is validated.
2020-06-02T10:42:30.4675677Z ##[debug]00:00:05.6529419 Calling 'NuGetRequest'::'GetPackageById', 'NuGet'.
2020-06-02T10:42:30.6912030Z ##[debug]00:00:05.8822684 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'NuGet'.
2020-06-02T10:42:30.6953384Z ##[debug]00:00:05.8824779 Calling 'NuGetClient'::'FindPackage'.
2020-06-02T10:42:30.6999981Z ##[debug]Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='NuGet'' for ''.
2020-06-02T10:42:30.7044269Z ##[debug]00:00:05.8880022 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='NuGet'&$skip=0&$top=40'.
2020-06-02T10:42:31.2645901Z ##[debug]00:00:06.4550033 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='NuGet'&$skip=0&$top=40'.
2020-06-02T10:42:31.2699720Z ##[debug]00:00:06.4564776 '3' packages received in the last request.
2020-06-02T10:42:31.2955718Z ##[debug]Total package yield:'1' for the specified package 'NuGet'.
2020-06-02T10:42:31.3006863Z ##[debug]00:00:06.4880319 Completed iterating for 'NuGet'.
2020-06-02T10:42:31.9288680Z ##[debug]00:00:07.1207697 Done calling powershell Â«Find-PackageÂ» Â«PSModuleÂ»
2020-06-02T10:42:31.9391317Z ##[debug]Importing the package provider 
2020-06-02T10:42:31.9442543Z ##[debug]00:00:03.5453394 Calling ImportPackageProvider. providerName = 'nuget', requiredVersion='2.8.5.208', minimumVersion = '', maximumVersion=''
2020-06-02T10:42:31.9525911Z ##[debug]00:00:03.5454412 Calling ImportPackageProviderViaName. providerName = 'nuget', requiredVersion='2.8.5.208', minimumVersion = '', maximumVersion=''
2020-06-02T10:42:31.9592977Z ##[debug]The provider 'NuGet' has already been imported. Trying to import it again.
2020-06-02T10:42:31.9657990Z ##[debug]00:00:03.5607687 Calling ImportPackageProviderViaPath. providerName = 'C:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll', requiredVersion='2.8.5.208', minimumVersion = '', maximumVersion=''
2020-06-02T10:42:31.9704923Z ##[debug]Loading an assembly 'C:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll'.
2020-06-02T10:42:31.9782599Z ##[debug]00:00:03.5610461 Trying provider assembly: C:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
2020-06-02T10:42:31.9830708Z ##[debug]00:00:03.5652264 Attempting loading of assembly: C:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
2020-06-02T10:42:31.9890409Z ##[debug]00:00:03.5653376 Acquiring providers for assemblyC:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
2020-06-02T10:42:31.9962334Z ##[debug]00:00:03.5676937 Initializing provider 'NuGet'
2020-06-02T10:42:32.0015017Z ##[debug]00:00:03.5773750 Calling 'NuGet'::'InitializeProvider'.
2020-06-02T10:42:32.0064775Z ##[debug]00:00:03.5774351 Provider 'NuGet' Initialized
2020-06-02T10:42:32.0118268Z ##[debug]00:00:03.5774846 Using Package Provider NuGet
2020-06-02T10:42:32.0177460Z ##[debug]00:00:03.5856157 Calling 'NuGet'::'GetFeatures'.
2020-06-02T10:42:32.0225213Z ##[debug]00:00:03.5861646 The provider 'NuGet' is imported
2020-06-02T10:42:32.0276931Z ##[debug]00:00:03.5870381 SUCCESS provider assembly: C:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
2020-06-02T10:42:32.0326089Z ##[debug]Imported provider 'C:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll' .
2020-06-02T10:42:32.0401221Z ##[debug]Setting nuget package source in D:\agents\agent-1\_work\7\_t\PA_BT\nuget.config
2020-06-02T10:42:32.7002433Z ##[debug]00:00:00.0000005 Calling 'NuGet'::'ResolvePackageSources'.
2020-06-02T10:42:32.7067877Z ##[debug]00:00:00.0009234 There are '1' registered sources in 'NuGet' provider.
2020-06-02T10:42:32.7206775Z ##[debug]00:00:00.0010224 nuget.org
2020-06-02T10:42:32.7260030Z ##[debug]00:00:00.0011777 Yielding the package source: 'Â«0Â»'. Â«NuGetÂ» Â«Microsoft.PackageManagement.NuGetProvider.PackageSourceÂ»
2020-06-02T10:42:32.7327887Z ##[debug]00:00:00.0018139 Yielding packge source for nuget.org at location https://api.nuget.org/v3/index.json
2020-06-02T10:42:32.7382607Z ##[debug]00:00:00.0019455 Returning the call 'NuGet'::'ResolvePackageSources'.
2020-06-02T10:42:32.7438934Z ##[debug]Performing the operation "MSG:ActionReplacePackageSource" on target "Package Source 'nuget.org' (https://api.nuget.org/v3/index.json) in provider 'NuGet'.".
2020-06-02T10:42:32.7590809Z ##[debug]00:00:00.0613088 Calling 'NuGet'::'RemovePackageSource'.
2020-06-02T10:42:32.7638354Z ##[debug]00:00:00.0614715 Calling 'NuGetRequest'::'FindRegisteredSource', 'nuget.org'.
2020-06-02T10:42:32.7686548Z ##[debug]00:00:00.0616922 Calling 'NuGetRequest'::'RemovePackageSource', 'nuget.org'.
2020-06-02T10:42:32.7765285Z ##[debug]00:00:00.0628360 Loading a configuration from file 'D:\agents\agent-1\_work\7\_t\PA_BT\nuget.config'.
2020-06-02T10:42:32.7851254Z ##[debug]00:00:00.0634709 Loaded a configuration from file 'D:\agents\agent-1\_work\7\_t\PA_BT\nuget.config'.
2020-06-02T10:42:32.7936276Z ##[debug]00:00:00.0648222 Yielding packge source for nuget.org at location https://api.nuget.org/v3/index.json
2020-06-02T10:42:32.8340744Z ##[debug]Overwriting package source 'nuget.org'.
2020-06-02T10:42:32.8382597Z ##[debug]Performing the operation "Register Package Source." on target "Package Source 'nuget.org' (https://www.nuget.org/api/v2) in provider 'NuGet'.".
2020-06-02T10:42:32.8567050Z ##[debug]00:00:00.1588208 AddPackageSource - ProviderName = 'NuGet', name='nuget.org', location='https://www.nuget.org/api/v2', trusted='True'
2020-06-02T10:42:32.8632417Z ##[debug]00:00:00.1589641 Calling 'NuGet'::'GetOptionValue'.
2020-06-02T10:42:32.8677807Z ##[debug]00:00:00.1591333 'IsUpdate' is 'False'.
2020-06-02T10:42:32.8726554Z ##[debug]00:00:00.1592224 Calling 'NuGet'::'FindRegisteredSource -name'nuget.org''.
2020-06-02T10:42:32.8786216Z ##[debug]00:00:00.1593398 Calling 'NuGetRequest'::'FindRegisteredSource', 'nuget.org'.
2020-06-02T10:42:32.8867247Z ##[debug]Error record:
2020-06-02T10:42:33.2124367Z ##[debug]Register-PackageSource : Package Source 'nuget.org' exists.
2020-06-02T10:42:33.2164326Z ##[debug]At D:\agents\agent-1\_work\_tasks\PowerAppsToolInstaller_70e9ed60-670f-11e9-be16-a150d2ff01e4\0.3.6\ToolInstaller.ps1:58 char:5
2020-06-02T10:42:33.2202621Z ##[debug]+     Register-PackageSource -Name $PackageSourceName -Location $Packag ...
2020-06-02T10:42:33.2234621Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-06-02T10:42:33.2273114Z ##[debug]    + CategoryInfo          : InvalidArgument: (nuget.org:String) [Register-PackageSource], Exception
2020-06-02T10:42:33.2324694Z ##[debug]    + FullyQualifiedErrorId : PackageSourceExists,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource
2020-06-02T10:42:33.2383775Z ##[debug] 
2020-06-02T10:42:33.2479474Z ##[debug]Script stack trace:
2020-06-02T10:42:33.2648288Z ##[debug]at Set-NugetSource, D:\agents\agent-1\_work\_tasks\PowerAppsToolInstaller_70e9ed60-670f-11e9-be16-a150d2ff01e4\0.3.6\ToolInstaller.ps1: line 58
2020-06-02T10:42:33.2693085Z ##[debug]at <ScriptBlock>, D:\agents\agent-1\_work\_tasks\PowerAppsToolInstaller_70e9ed60-670f-11e9-be16-a150d2ff01e4\0.3.6\ToolInstaller.ps1: line 142
2020-06-02T10:42:33.2746289Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-02T10:42:33.2806886Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-06-02T10:42:33.2840520Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-06-02T10:42:33.2880003Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-02T10:42:33.2962564Z ##[debug]Exception:
2020-06-02T10:42:33.3121472Z ##[debug]System.Exception: Package Source 'nuget.org' exists.
2020-06-02T10:42:33.3559934Z ##[error]Package Source 'nuget.org' exists.
2020-06-02T10:42:33.3590998Z ##[debug]Processed: ##vso[task.logissue type=error]Package Source 'nuget.org' exists.
2020-06-02T10:42:33.3593038Z Installing nuget pkg Microsoft.CrmSdk.CoreTools - 9.1.0.43 ...
2020-06-02T10:42:34.4001164Z ##[debug]00:00:00.0000004 Calling 'Programs::GetDynamicOptions' 'Provider'
2020-06-02T10:42:34.4056845Z ##[debug]00:00:00.0098209 Calling 'Programs::GetDynamicOptions' 'Source'
2020-06-02T10:42:34.4114212Z ##[debug]00:00:00.0202713 Calling 'Programs::GetDynamicOptions' 'Package'
2020-06-02T10:42:34.4165685Z ##[debug]00:00:00.0303965 Calling 'Programs::GetDynamicOptions' 'Install'
2020-06-02T10:42:34.4217307Z ##[debug]00:00:00.0565338 Calling 'msu::GetDynamicOptions' 'Provider'
2020-06-02T10:42:34.4277193Z ##[debug]00:00:00.0689970 Calling 'msu::GetDynamicOptions' 'Source'
2020-06-02T10:42:34.4329170Z ##[debug]00:00:00.0781795 Calling 'msu::GetDynamicOptions' 'Package'
2020-06-02T10:42:34.4381784Z ##[debug]00:00:00.0896791 Calling 'msu::GetDynamicOptions' 'Install'
2020-06-02T10:42:34.4431929Z ##[debug]00:00:00.1252525 Calling 'msi::GetDynamicOptions' 'Provider'
2020-06-02T10:42:34.4480100Z ##[debug]00:00:00.1364302 Calling 'msi::GetDynamicOptions' 'Source'
2020-06-02T10:42:34.4530564Z ##[debug]00:00:00.1459642 Calling 'msi::GetDynamicOptions' 'Package'
2020-06-02T10:42:34.4577524Z ##[debug]00:00:00.1634994 Calling 'msi::GetDynamicOptions' 'Install'
2020-06-02T10:42:34.4622305Z ##[debug]00:00:00.2491879 Calling New() : MethodName = 'GetDynamicOptions'
2020-06-02T10:42:34.4674059Z ##[debug]00:00:00.2493104 Force: True
2020-06-02T10:42:34.4719418Z ##[debug]00:00:00.2493781 RequiredVersion: 9.1.0.43
2020-06-02T10:42:34.4765822Z ##[debug]00:00:00.2494253 Name: Microsoft.CrmSdk.CoreTools
2020-06-02T10:42:34.4829252Z ##[debug]00:00:00.2522887 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
2020-06-02T10:42:34.4901424Z ##[debug]00:00:00.3274949 In PowerShellGet Provider - 'Get-DynamicOptions'.
2020-06-02T10:42:34.4969008Z ##[debug]00:00:00.3736713 Done calling powershell Â«Get-DynamicOptionsÂ» Â«PSModuleÂ»
2020-06-02T10:42:34.5015542Z ##[debug]00:00:00.3845767 Calling New() : MethodName = 'GetDynamicOptions'
2020-06-02T10:42:34.5059838Z ##[debug]00:00:00.3846525 Force: True
2020-06-02T10:42:34.5118711Z ##[debug]00:00:00.3847185 RequiredVersion: 9.1.0.43
2020-06-02T10:42:34.5163974Z ##[debug]00:00:00.3847692 Name: Microsoft.CrmSdk.CoreTools
2020-06-02T10:42:34.5217636Z ##[debug]00:00:00.3870354 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
2020-06-02T10:42:34.5263058Z ##[debug]00:00:00.3888677 In PowerShellGet Provider - 'Get-DynamicOptions'.
2020-06-02T10:42:34.5321156Z ##[debug]00:00:00.3958603 Done calling powershell Â«Get-DynamicOptionsÂ» Â«PSModuleÂ»
2020-06-02T10:42:34.5378534Z ##[debug]00:00:00.4059269 Calling New() : MethodName = 'GetDynamicOptions'
2020-06-02T10:42:34.5434645Z ##[debug]00:00:00.4060011 Force: True
2020-06-02T10:42:34.5480472Z ##[debug]00:00:00.4060548 RequiredVersion: 9.1.0.43
2020-06-02T10:42:34.5524411Z ##[debug]00:00:00.4061043 Name: Microsoft.CrmSdk.CoreTools
2020-06-02T10:42:34.5579495Z ##[debug]00:00:00.4078030 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
2020-06-02T10:42:34.5623102Z ##[debug]00:00:00.4095323 In PowerShellGet Provider - 'Get-DynamicOptions'.
2020-06-02T10:42:34.5668955Z ##[debug]00:00:00.4292815 Done calling powershell Â«Get-DynamicOptionsÂ» Â«PSModuleÂ»
2020-06-02T10:42:34.5776117Z ##[debug]00:00:00.4512810 Calling New() : MethodName = 'GetDynamicOptions'
2020-06-02T10:42:34.5832358Z ##[debug]00:00:00.4513576 Force: True
2020-06-02T10:42:34.5881433Z ##[debug]00:00:00.4514113 RequiredVersion: 9.1.0.43
2020-06-02T10:42:34.5944575Z ##[debug]00:00:00.4514623 Name: Microsoft.CrmSdk.CoreTools
2020-06-02T10:42:34.5997658Z ##[debug]00:00:00.4535612 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
2020-06-02T10:42:34.6056602Z ##[debug]00:00:00.4554265 In PowerShellGet Provider - 'Get-DynamicOptions'.
2020-06-02T10:42:34.6122360Z ##[debug]00:00:00.4665813 Done calling powershell Â«Get-DynamicOptionsÂ» Â«PSModuleÂ»
2020-06-02T10:42:34.6287442Z ##[debug]00:00:00.6973846 Calling SearchForPackages. Name='Microsoft.CrmSdk.CoreTools'
2020-06-02T10:42:34.6354900Z ##[debug]Using the provider 'NuGet' for searching packages.
2020-06-02T10:42:34.6424231Z ##[debug]00:00:00.7003869 PackageProvider::FindPackage with name Microsoft.CrmSdk.CoreTools
2020-06-02T10:42:34.6479017Z ##[debug]00:00:00.7011848 Calling SearchForPackages After Select 1
2020-06-02T10:42:34.6529267Z ##[debug]00:00:00.7077938 Calling 'NuGet'::'FindPackage' - name='Microsoft.CrmSdk.CoreTools', requiredVersion='9.1.0.43',minimumVersion='', maximumVersion='''.
2020-06-02T10:42:34.6576888Z ##[debug]00:00:00.7079255 Iterating 'Microsoft.CrmSdk.CoreTools'.
2020-06-02T10:42:34.6625866Z ##[debug]00:00:00.7083390 There are '1' registered sources in 'NuGet' provider.
2020-06-02T10:42:34.6693912Z ##[debug]00:00:00.7084339 nuget.org
2020-06-02T10:42:34.6744033Z ##[debug]00:00:00.7085208 Calling 'NuGetRequest'::'GetPackageById', 'Microsoft.CrmSdk.CoreTools'.
2020-06-02T10:42:35.1164284Z ##[debug]00:00:01.1840752 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'Microsoft.CrmSdk.CoreTools'.
2020-06-02T10:42:35.1222462Z ##[debug]00:00:01.1842470 Calling 'NuGetClient'::'FindPackage'.
2020-06-02T10:42:35.1284469Z ##[debug]Searching repository 'https://api.nuget.org/v3/index.json/FindPackagesById()?id='Microsoft.CrmSdk.CoreTools'' for ''.
2020-06-02T10:42:35.1343611Z ##[debug]00:00:01.1845900 Downloading 'https://api.nuget.org/v3/index.json/FindPackagesById()?id='Microsoft.CrmSdk.CoreTools'&$skip=0&$top=40'.
2020-06-02T10:42:35.1427831Z ##[debug]00:00:01.2099932 Completed downloading 'https://api.nuget.org/v3/index.json/FindPackagesById()?id='Microsoft.CrmSdk.CoreTools'&$skip=0&$top=40'.
2020-06-02T10:42:35.1632965Z ##[debug]00:00:01.2246595 System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
2020-06-02T10:42:35.1675122Z ##[debug]   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2020-06-02T10:42:35.1715936Z ##[debug]   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
2020-06-02T10:42:35.1763096Z ##[debug]   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
2020-06-02T10:42:35.1804886Z ##[debug]   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
2020-06-02T10:42:35.1856609Z ##[debug]   at Microsoft.PackageManagement.Provider.Utility.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
2020-06-02T10:42:35.1885314Z ##[debug]   at Microsoft.PackageManagement.NuGetProvider.HttpClientPackageRepository.<SendRequest>d__10.MoveNext()
2020-06-02T10:42:35.1926975Z ##[debug]   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2020-06-02T10:42:35.1964534Z ##[debug]   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
2020-06-02T10:42:35.2013034Z ##[debug]   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
2020-06-02T10:42:35.2058536Z ##[debug]   at System.Linq.Parallel.SpoolingTaskBase.Work()
2020-06-02T10:42:35.2121632Z ##[debug]   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
2020-06-02T10:42:35.2184115Z ##[debug]   at System.Threading.Tasks.Task.Execute()
2020-06-02T10:42:35.2229374Z ##[debug]   --- End of inner exception stack trace ---
2020-06-02T10:42:35.2269860Z ##[debug]   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
2020-06-02T10:42:35.2310913Z ##[debug]   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
2020-06-02T10:42:35.2347269Z ##[debug]   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
2020-06-02T10:42:35.2385106Z ##[debug]   at Microsoft.PackageManagement.NuGetProvider.NuGetRequest.YieldPackages(IEnumerable`1 packageReferences, String searchKey)
2020-06-02T10:42:35.2429324Z ##[debug]   at Microsoft.PackageManagement.NuGetProvider.NuGetProvider.FindPackage(String name, String requiredVersion, String minimumVersion, String maximumVersion, Int32 id, NuGetRequest request)
2020-06-02T10:42:35.2464349Z ##[debug]---> (Inner Exception #0) System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
2020-06-02T10:42:35.2501884Z ##[debug]   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2020-06-02T10:42:35.2536918Z ##[debug]   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
2020-06-02T10:42:35.2572584Z ##[debug]   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
2020-06-02T10:42:35.2607498Z ##[debug]   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
2020-06-02T10:42:35.2643432Z ##[debug]   at Microsoft.PackageManagement.Provider.Utility.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
2020-06-02T10:42:35.2678805Z ##[debug]   at Microsoft.PackageManagement.NuGetProvider.HttpClientPackageRepository.<SendRequest>d__10.MoveNext()
2020-06-02T10:42:35.2714849Z ##[debug]   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2020-06-02T10:42:35.2752010Z ##[debug]   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
2020-06-02T10:42:35.2793573Z ##[debug]   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
2020-06-02T10:42:35.2828239Z ##[debug]   at System.Linq.Parallel.SpoolingTaskBase.Work()
2020-06-02T10:42:35.2872634Z ##[debug]   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
2020-06-02T10:42:35.2903672Z ##[debug]   at System.Threading.Tasks.Task.Execute()<---
2020-06-02T10:42:35.2938949Z ##[debug]
2020-06-02T10:42:35.3007096Z ##[debug]00:00:01.3704226 unmatched package name='Microsoft.CrmSdk.CoreTools'
2020-06-02T10:42:35.3231421Z ##[debug]Leaving D:\agents\agent-1\_work\_tasks\PowerAppsToolInstaller_70e9ed60-670f-11e9-be16-a150d2ff01e4\0.3.6\ToolInstaller.ps1.
2020-06-02T10:42:35.3386909Z ##[debug]Caught exception from task script.
2020-06-02T10:42:35.3463128Z ##[debug]Error record:
2020-06-02T10:42:35.4544112Z ##[debug]Install-Package : No match was found for the specified search criteria and package name 'Microsoft.CrmSdk.CoreTools'. Try Get-PackageSource to see all available registered package sources.
2020-06-02T10:42:35.4568492Z ##[debug]At D:\agents\agent-1\_work\_tasks\PowerAppsToolInstaller_70e9ed60-670f-11e9-be16-a150d2ff01e4\0.3.6\ToolInstaller.ps1:71 char:5
2020-06-02T10:42:35.4591499Z ##[debug]+     Install-Package $PackageName -RequiredVersion $PackageVersion -De ...
2020-06-02T10:42:35.4619478Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-06-02T10:42:35.4640963Z ##[debug]    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex    ception
2020-06-02T10:42:35.4670904Z ##[debug]    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
2020-06-02T10:42:35.4693000Z ##[debug] 
2020-06-02T10:42:35.4777562Z ##[debug]Script stack trace:
2020-06-02T10:42:35.4815607Z ##[debug]at Install-NuGetPackage, D:\agents\agent-1\_work\_tasks\PowerAppsToolInstaller_70e9ed60-670f-11e9-be16-a150d2ff01e4\0.3.6\ToolInstaller.ps1: line 71
2020-06-02T10:42:35.4844473Z ##[debug]at <ScriptBlock>, D:\agents\agent-1\_work\_tasks\PowerAppsToolInstaller_70e9ed60-670f-11e9-be16-a150d2ff01e4\0.3.6\ToolInstaller.ps1: line 144
2020-06-02T10:42:35.4873112Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-02T10:42:35.4894776Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-06-02T10:42:35.4917080Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-06-02T10:42:35.4937945Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-02T10:42:35.4982044Z ##[debug]Exception:
2020-06-02T10:42:35.5025920Z ##[debug]System.Exception: No match was found for the specified search criteria and package name 'Microsoft.CrmSdk.CoreTools'. Try Get-PackageSource to see all available registered package sources.
2020-06-02T10:42:35.5064974Z ##[error]No match was found for the specified search criteria and package name 'Microsoft.CrmSdk.CoreTools'. Try Get-PackageSource to see all available registered package sources.
2020-06-02T10:42:35.5074673Z ##[debug]Processed: ##vso[task.logissue type=error]No match was found for the specified search criteria and package name 'Microsoft.CrmSdk.CoreTools'. Try Get-PackageSource to see all available registered package sources.
2020-06-02T10:42:35.5107360Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-06-02T10:42:35.5980540Z ##[section]Finishing: PowerAppsToolInstaller


Any ideas ?

**Comment by scberr** [comment]
I'm getting this error too. 

It is occurring on an On-Premises DevOps Services Agent.

@JeroenDaniels Let me know if you find a work around

**Comment by JeroenDaniels** [comment]
@scberr 

It is working on our agents now, i tried a lot of things so i'm sorry but i can not tell you specifically what solved it. It had something to do with NuGet on the machine. 
So first install it manually on the Agent.

Secondly i added this YAML step at the beginning of the pipeline to unregister the packageSource:

- task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'Unregister-PackageSource -name nuget.org'
            errorActionPreference: 'continue'


I hope this helps you.
