### ISSUE TITLE
PowerPlatformExportSolution task error "You cannot call a method on a null-valued expression."

### ISSUE THREAD

**Issue by umerjaved** [microsoft/PowerApps-Samples#126]
Hi,

I have been following the guideline given in the PDF document. I created a build pipeline however it seems to fail on the export solution task with following error, any ideas for fix will be highly appreciated.

##[debug]    + CategoryInfo          : InvalidOperation: (:) [ExportSolution.ps1], RuntimeException
##[debug]    + FullyQualifiedErrorId : InvokeMethodOnNull,ExportSolution.ps1
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, D:\a\_tasks\PowerPlatformExportSolution_16f6dae7-e6ef-4629-ae75-7988463cb6a6\0.0.1\ExportSolution.ps1: line 75
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
##[error]You cannot call a method on a null-valued expression.
##[debug]Processed: ##vso[task.logissue type=error]****You cannot call a method on a null-valued expression.****
##[debug]Processed: ##vso[task.complete result=Failed]
Finishing: Power Platform Export Solution

**Comment by umerjaved** [comment]
Found the issue with export, i missed the task "Power platform tool installer" from the documentation
