### ISSUE TITLE
Error while using connection string: Metadata contains a reference that cannot be resolved 

### ISSUE THREAD

**Issue by devudu** [microsoft/PowerApps-Samples#178]
For some reason when I tried to use connection string instead of interactive form I am getting the below error. Is there any workaround to make this work?

Error log:

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source      : System.ServiceModel
Method  : Retrieve
Date    : 3/19/2021
Time    : 7:04:43 PM
Error   : Metadata contains a reference that cannot be resolved: 'https://{myenv}.api.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
Stack Trace     : at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri address, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source  : System
Method  : GetResponse
Date    : 3/19/2021
Time    : 7:04:43 PM
Error   : The remote name could not be resolved: '{myenv}.api.crm.dynamics.com'
Stack Trace     : at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
```

**Comment by Nkrb** [comment]
@devudu Can you let us know what exact sample you're trying, so that we can identify the issue.

**Comment by devudu** [comment]
@Nkrb its common error for all C# samples. Example

https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/C%23/CreateUpdateEntityMetadata

**Comment by Nkrb** [comment]
@devudu We don't see any issue when we use the samples. Can you paste the connection string you are using to connect to an environment. Are you using OAuth as AuthType? Are you able to connect to the environment using the Login screen instead of the connection string?

**Comment by devudu** [comment]
@Nkrb 
I used default AppId and RedeirectUri
	  ```
<add name="Connect"
         connectionString="Url=https://mysite.api.crm.dynamics.com;
		 AuthType=OAuth;
         UserName=myname@mydomain.onmicrosoft.com;
		 Password=myverystrongpassword;
		 AppId=51f81489-12ee-4a9e-aaae-a2591f45987d;
         RedirectUri=app://58145B91-0C36-4500-8554-080854F2AC97;
		 LoginPrompt=Auto
         "/>
```

**Comment by Nkrb** [comment]
@devudu Can you modify the URL by removing the api term and see if you can connect.

**Comment by devudu** [comment]
@Nkrb Same error message after removing api from url
However, when I tried to change .crm to .crm8 I got a different error its same message with and without api
Url=https://mysite.crm8.dynamics.com; and Url=https://mysite.api.crm8.dynamics.com;

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source      : Microsoft.Xrm.Sdk
Method  : .ctor
Date    : 4/8/2021
Time    : 1:01:41 PM
Error   : Data[0] = "The provided uri did not return any Service Endpoints!
{0}"
Data[1] = ""
Stack Trace     : at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
The application terminated with an error.
Press <Enter> to exit.
```

**Comment by devudu** [comment]
@Nkrb Same error without api. I revisited older POCs and found my URL is actually slightly different. Its using .crm8 instead of .crm changing to Url=https://mysite.api.crm8.dynamics.com worked. Thanks for your time.
