### ISSUE TITLE
You must enable HTTP Activation on your computer to run the QuickStartForDynamics365 sample

### ISSUE THREAD

**Issue by JimDaly** [microsoft/PowerApps-Samples#18]
Running the this sample:
PowerApps-Samples\cds\orgsvc\C#\QuickStartForDynamics365\QuickStartForDynamics365\SampleProgram.cs
Got this error: 
```
Source	: System.Web
Method	: .ctor
Date	: 6/5/2019
Time	: 7:18:08 PM
Error	: Unable to initialize the native configuration support external to the web worker process (HRESULT=0x80040154).
nativerd.dll must be in %windir%\system32\inetsrv.
Stack Trace	: at System.Web.Configuration.ProcessHostConfigUtils.NativeConfigWrapper..ctor()
   at System.Web.Configuration.ProcessHostConfigUtils.InitStandaloneConfig()
   at System.Web.Configuration.ProcessHostMapPath..ctor(IProcessHostSupportFunctions functions)
   at System.Web.Configuration.IISMapPath.GetInstance()
   at System.Web.Configuration.WebConfigurationHost.ChooseAndInitConfigMapPath(Boolean useConfigMapPath, IConfigMapPath configMapPath, ConfigurationFileMap fileMap)
   at System.Web.Configuration.WebConfigurationHost.InitForConfiguration(String& locationSubPath, String& configPath, String& locationConfigPath, IInternalConfigRoot configRoot, Object[] hostInitConfigurationParams)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.Internal.InternalConfigConfigurationFactory.System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Web.Configuration.WebConfigurationHost.OpenConfiguration(WebLevel webLevel, ConfigurationFileMap fileMap, VirtualPath path, String site, String locationSubPath, String server, String userName, String password, IntPtr tokenHandle)
   at System.Web.Hosting.HostingEnvironment.get_CacheStoreProviderSettings()
   at System.Web.Caching.Cache.GetObjectCache(Boolean createIfDoesNotExist)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetCachedCRMService(CrmWebSvc& ConnectionObject)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.IntilizeService(CrmWebSvc& ConnectionObject)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DoLogin(CrmWebSvc& ConnectionObject)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CreateCRMWebServiceConnection(OrganizationServiceProxy externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId, SecureString password, String domain, String CrmOnlineRegion, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, OrganizationWebProxyClient externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient..ctor(String crmUserId, SecureString crmPassword, String crmRegion, String orgName, Boolean useUniqueInstance, OrganizationDetail orgDetail, UserIdentifier user, String clientId, Uri redirectUri, String tokenCachePath, OrganizationWebProxyClient externalOrgWebProxyClient, PromptBehavior promptBehavior)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ConnectAndInitCrmOrgService(CrmOrgByServer orgdata)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================
```
Found that I needed to enable HTTP Activation

![image](https://user-images.githubusercontent.com/6353736/59002553-ab148080-87c7-11e9-8906-0f19a9dac67e.png)

Thanks to this issue [MscrmTools/XrmToolBox Unable to initialize the native configuration support external to the web worker process](https://github.com/MscrmTools/XrmToolBox/issues/778)

This requirement should be added to prerequisites for running samples. Seems to be a prerequisite for using the Xrm.Tooling dialog used by this sample.

**Comment by brendon-colburn** [comment]
This messes with Plugin Registration tool as well.

**Comment by KumarVivek** [comment]
This is a known issue, and is documented here now: https://github.com/microsoft/PowerApps-Samples/tree/master/cds#known-issue

Thanks for raising this @JimDaly. Closing this.
