### ISSUE TITLE
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set / spark_home not set / exception in worker process

### ISSUE THREAD

**Issue by rhpoon** [microsoft/PowerApps-Samples#234]
I came across the following spark worker node issue that might be related to the gunicorn gateway inference server running Spark?
(The last pandas not found incurred on this server? i noted pandas module not found error, and the gunicorn requires python 3.7 so would the score.py need somekind of reconfiguration to be validated?)https://docs.microsoft.com/en-us/azure/machine-learning/how-to-inference-server-http

2022-01-11T07:22:51,350423000+00:00 - rsyslog/run 
2022-01-11T07:22:51,356648500+00:00 - gunicorn/run 
2022-01-11T07:22:51,355747300+00:00 - iot-server/run 
2022-01-11T07:22:51,381952900+00:00 - nginx/run 
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2022-01-11T07:22:51,595759100+00:00 - iot-server/finish 1 0
2022-01-11T07:22:51,599248900+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 20.1.0 ****
Listening at: http://127.0.0.1:31311 (454)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 484
SPARK_HOME not set. Skipping PySpark Initialization. *****
Exception in worker process
Traceback (most recent call last):
  File "/azureml-envs/azureml_b40613e65d875dd6f39858a7ef2209be/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/azureml-envs/azureml_b40613e65d875dd6f39858a7ef2209be/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/azureml-envs/azureml_b40613e65d875dd6f39858a7ef2209be/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/azureml-envs/azureml_b40613e65d875dd6f39858a7ef2209be/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/azureml-envs/azureml_b40613e65d875dd6f39858a7ef2209be/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/azureml-envs/azureml_b40613e65d875dd6f39858a7ef2209be/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/azureml-envs/azureml_b40613e65d875dd6f39858a7ef2209be/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/azureml-envs/azureml_b40613e65d875dd6f39858a7ef2209be/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/azureml-server/wsgi.py", line 1, in <module>
    import create_app
  File "/var/azureml-server/create_app.py", line 3, in <module>
    from app import main
  File "/var/azureml-server/app.py", line 32, in <module>
    from aml_blueprint import AMLBlueprint
  File "/var/azureml-server/aml_blueprint.py", line 23, in <module>
    main_module_spec.loader.exec_module(main)
  File "/var/azureml-app/score.py", line 16, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas' ******
Worker exiting (pid: 484)
Shutting down: Master
Reason: Worker failed to boot.

**Comment by rhpoon** [comment]
I also tried Python 3.8 with similar error:  (I may try to see if I can explicitly do Conda install pandas or pip install pandas (this is a pure azureml cloud notebook and deployment. My last run shows the failure is at line 16 of score.py: import pandas as pd.

Error:
{
  "code": "AciDeploymentFailed",
  "statusCode": 400,
  "message": "Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'pandas', please run print(service.get_logs()) to get details.",
  "details": [
    {
      "code": "CrashLoopBackOff",
      "message": "Error in entry script, ModuleNotFoundError: No module named 'pandas', please run print(service.get_logs()) to get details."
    }
  ]
}

**Comment by rhpoon** [comment]
I can confirm that adding 'pandas' to pip section of myenv.yml file solve the problem. Perhaps it is worth to note  and see if using version version specification also solve the problem (no idea what conda install using that 'zureml-defaults' specified in the yml file):

The conda environment file specifies the dependencies for the service. It includes dependencies required by both the model and the entry script. Please note that you must indicate azureml-defaults with verion >= 1.0.45 as a pip dependency, because it contains the functionality needed to host the model as a web service

https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/machine-learning/how-to-deploy-inferencing-gpus.md

**Comment by phecke** [comment]
@rhpoon Is this issue related to one of our samples? Which one?

**Comment by phecke** [comment]
@rhpoon No response, and not related to a code sample. Closing.
