### ISSUE TITLE
Cannot Find Org in GCC / North America 2

### ISSUE THREAD

**Issue by richxyz** [microsoft/PowerApps-Samples#240]
I have tried Don't Know and North America 2 but the GenerateEntityDiagram.exe cannot find my orgs which are in the GCC government cloud.   I tried with and without the advanced option checkbox.   It appears that this tool will not work with orgs in the government cloud.

Microsoft.Xrm.Tooling.CrmConnectControl Error: 2 : Error Message: Can't connect to Microsoft Dynamics CRM - .
Source : Microsoft.IdentityModel.Clients.ActiveDirectory
Method : RunAsyncTask
Date : 2/18/2022
Time : 10:19:08 AM
Error : unknown_user_type: Unknown User Type

**Comment by MattB-msft** [comment]
Please update the nuget dependencies to current for all of the Microsoft.crmsdk.* assemblies

Let us know if that does not solve it for you.

Thanks
________________________________
From: richxyz ***@***.***>
Sent: Friday, February 18, 2022 8:17:06 AM
To: microsoft/PowerApps-Samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/PowerApps-Samples] Cannot Find Org in GCC / North America 2 (Issue #240)


I have tried Don't Know and North America 2 but the GenerateEntityDiagram.exe cannot find my orgs which are in the GCC government cloud. I tried with and without the advanced option checkbox. It appears that this tool will not work with orgs in the government cloud.

Microsoft.Xrm.Tooling.CrmConnectControl Error: 2 : Error Message: Can't connect to Microsoft Dynamics CRM - .
Source : Microsoft.IdentityModel.Clients.ActiveDirectory
Method : RunAsyncTask
Date : 2/18/2022
Time : 10:19:08 AM
Error : unknown_user_type: Unknown User Type

**Comment by richxyz** [comment]
I updated all dependencies and recompiled.  Now I get a different error.


Source	: Not Provided
Method	: Not Provided
Date	: 2/18/2022
Time	: 9:56:14 AM
Error	: A CRM server name is required.
Parameter name: CrmServerName
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 2/18/2022
Time	: 12:07:55 PM
Error	: A CDS server name is required.
Parameter name: CrmServerName
Stack Trace	: Not Provided
======================================================================================================================

Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 2/18/2022
Time	: 12:08:29 PM
Error	: unknown_user_type: Unknown User Type
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ProcessAdalExecption(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier& user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink, Boolean useDefaultCreds, String& authToken, AdalException adalEx)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================

**Comment by MattB-msft** [comment]
Can you pull down the current plugin Registration tool and attempt to login? 
If it works, we can narrow it down to this project. 

Thanks.

**Comment by richxyz** [comment]
I figured out what I was doing wrong.  There is a new region I need to specify...  now I can find my orgs.  Thanks for your help!

**Comment by MattB-msft** [comment]
Yep, USG and DOD are different clouds from GCC
