### ISSUE TITLE
AngularJS Flip Control - Uncaught TypeError

### ISSUE THREAD

**Issue by DeanB2015** [microsoft/PowerApps-Samples#251]
Using `NPM start`, I get the following error in the PCF Control Sandbox.  The sandbox content does not display and a blank screen appears.  Node version 12.18.3

Files = https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/AngularJSFlipControl

`
SimpleFormatter.ts:41 
        
       Uncaught TypeError: e.toLowerCase is not a function
    at Object.t.ParseRaw (SimpleFormatter.ts:41:34)
    at DefaultHostProps.ts:183:41
    at Array.forEach (<anonymous>)
    at f (DefaultHostProps.ts:181:42)
    at u (DefaultHostProps.ts:52:39)
    at Object.t.createWebClientWrapperProps (DefaultHostProps.ts:38:48)
    at t.render (ControlHost.tsx:85:15)
    at finishClassComponent (react-dom.development.js:17515:33)
    at updateClassComponent (react-dom.development.js:17465:26)
    at beginWork (react-dom.development.js:19103:18)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3991:18)
    at invokeGuardedCallback (react-dom.development.js:4053:33)
    at beginWork$1 (react-dom.development.js:23994:9)
    at performUnitOfWork (react-dom.development.js:22809:14)
    at workLoopSync (react-dom.development.js:22737:7)
`

**Comment by JimDaly** [comment]
@DeanB2015 
Sorry for the late reply. If you are still experiencing this problem, please re-open this issue

**Comment by JimDaly** [comment]
Thanks @rolf-weiglein-bizerba 
I can't repro this specific issue, I've got a different one. I'm going to reach out to the dev team.

**Comment by JimDaly** [comment]
@jopursle tells me he is working on a fix for this. Let's close this when those changes get pushed out.

**Comment by rolf-weiglein-bizerba** [comment]
> Thanks [@rolf-weiglein-bizerba](https://github.com/rolf-weiglein-bizerba) I can't repro this specific issue, I've got a different one. I'm going to reach out to the dev team.

Thanks @JimDaly

**Comment by rolf-weiglein-bizerba** [comment]
@JimDaly As I understand your approach with Angular Flip Control, you are creating the Angular app virtually in the DOM. Are there any ways to use an Angular app (created with ng new <app-name> in the PCF project) inside a PCF code control? I am currently having issues when I try to initialize the Angular app. It is not rendering in the PCF.
