### ISSUE TITLE
"Remove-RoleAssignmentFromUsers" throws error System.ArgumentNullException: Value cannot be null. Parameter name: path1

### ISSUE THREAD

**Issue by KiraXie2** [microsoft/PowerApps-Samples#413]
I run this command:
Remove-RoleAssignmentFromUsers -roleName "System Administrator"  -usersFilePath C:\temp\230404David.csv -processAllEnvironments $true -outputLogsDirectory C:\temp\DavidRemovedRoles

However, there is no successful role removement.
The error is:
Exception while retrieving users with role name System Administrator from environment https://zfsalescoretest.crm.dynamics.com : 
 System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.PowerPlatform.Administration.Helpers.Logger.GetRoleRemovalLogPath(String logLocation, String orgName, String roleName) in C:\Users\Z0147856\PowerApps-Samples\powershell\UserManagement\Microsoft.PowerPlatform.Administration.UserManagement\Microsoft.PowerPlatform.Administration.Helpers\Logger.cs:line 110
   at Microsoft.PowerPlatform.Administration.Helpers.EnvironmentOperationsHelper.RemoveRolesFromUsersInEnvironment(String userName, String password, String roleName, String environmentUrl, IList`1 userPrincipalNames) in C:\Users\Z0147856\PowerApps-Samples\powershell\UserManagement\Microsoft.PowerPlatform.Administration.UserManagement\Microsoft.PowerPlatform.Administration.Helpers\EnvironmentOperationsHelper.cs:line 116

**Comment by phecke** [comment]
@KiraXie2 Which code sample are you referring to?

**Comment by KiraXie2** [comment]
https://github.com/microsoft/PowerApps-Samples/tree/master/powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement

**Comment by krishnapallavi** [comment]
This was fixed as part of this PR. @KiraXie2 can you please pull the latest version and try?
