### ISSUE TITLE
Issue while importing a solution which contains PowerApps CanvasApp import: FAILURE: No file with that name found ---&gt; Microsoft.Crm.CrmArgumentException: No file with that name found ---&gt; System.ArgumentException: No file with that name found

### ISSUE THREAD

**Issue by rahulz55** [microsoft/PowerApps-Samples#512]
2023-12-12T07:37:08.4360205Z ##[section]Starting: Import Patch to dev
2023-12-12T07:37:08.4585096Z ==============================================================================
2023-12-12T07:37:08.4585257Z Task         : Power Platform Import Solution
2023-12-12T07:37:08.4585339Z Description  : Power Platform Import Solution
2023-12-12T07:37:08.4585428Z Version      : 0.0.89
2023-12-12T07:37:08.4585509Z Author       : Microsoft
2023-12-12T07:37:08.4585582Z Help         : [More Info](https://aka.ms/buildtoolsdoc)
2023-12-12T07:37:08.4585682Z ==============================================================================
2023-12-12T07:37:09.4121245Z ##[warning]This v0 of PP-BT, using a Powershell implementation, has been deprecated!. Please consult https://aka.ms/pp-bt-migrate-to-v2 on how to migrate your pipelines to PP-BT v2.
2023-12-12T07:37:09.5223594Z VERBOSE: InProcBindingRedirect: 2 - looking to resolve assembly: Microsoft.PowerShell.ConsoleHost.resources, 
2023-12-12T07:37:09.5224573Z Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
2023-12-12T07:37:09.5234403Z VERBOSE: InProcBindingRedirect: 1 - looking to resolve assembly: Microsoft.Xrm.WebApi.PowerShell
2023-12-12T07:37:09.5404076Z ##[warning]The names of some imported commands from the module 'Microsoft.Xrm.WebApi.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2023-12-12T07:37:09.8203487Z VERBOSE: InProcBindingRedirect: 3 - looking to resolve assembly: Microsoft.Extensions.Logging.Abstractions, 
2023-12-12T07:37:09.8279872Z Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
2023-12-12T07:37:09.8350329Z VERBOSE: InProcBindingRedirect: 4 - looking to resolve assembly: Microsoft.Extensions.Options, Version=3.1.8.0, 
2023-12-12T07:37:09.8350874Z Culture=neutral, PublicKeyToken=adb9793829ddae60
2023-12-12T07:37:09.8394768Z VERBOSE: InProcBindingRedirect: 5 - looking to resolve assembly: Microsoft.Extensions.DependencyInjection.Abstractions,
2023-12-12T07:37:09.8395517Z  Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
2023-12-12T07:37:09.8441330Z VERBOSE: InProcBindingRedirect: 6 - looking to resolve assembly: Microsoft.Extensions.DependencyInjection, 
2023-12-12T07:37:09.8442373Z Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
2023-12-12T07:37:09.8487708Z VERBOSE: InProcBindingRedirect: 7 - looking to resolve assembly: Microsoft.Extensions.Http, Version=3.1.8.0, 
2023-12-12T07:37:09.8488269Z Culture=neutral, PublicKeyToken=adb9793829ddae60
2023-12-12T07:37:11.1840238Z ****************************************************************************************************
2023-12-12T07:37:11.1842571Z Organization details
2023-12-12T07:37:11.1844783Z ****************************************************************************************************
2023-12-12T07:37:11.1846738Z 12/12/2023 7:37:11 AM | INFO | Connected Org Url: https://gsk-powerplatformcoe-dvm.crm.dynamics.com/
2023-12-12T07:37:11.1848523Z 12/12/2023 7:37:11 AM | INFO | Connected Org Id: 3896b712-2130-40ec-bc09-294ec1858a68
2023-12-12T07:37:11.1850157Z 12/12/2023 7:37:11 AM | INFO | Connected Org Friendly Name: Power Platform CoE - DvM
2023-12-12T07:37:11.1851784Z 12/12/2023 7:37:11 AM | INFO | Connected Org Unique Name: unq3896b712213040ecbc09294ec1858
2023-12-12T07:37:11.1855856Z 12/12/2023 7:37:11 AM | INFO | Connected Org Version: 9.2.23104.248
2023-12-12T07:37:24.3623204Z VERBOSE: InProcBindingRedirect: 8 - looking to resolve assembly: System.Management.Automation.resources, 
2023-12-12T07:37:24.3623773Z Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
2023-12-12T07:37:24.6305514Z ##[error]Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: CanvasApp import: FAILURE: No file with that name foundDetail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>33d24da6-0092-4635-b302-67d485bf3ea2</ActivityId>
  <ErrorCode>-2147188704</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionSourceKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Plugin/Microsoft.Crm.WebServices.ImportXmlService</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiSourceActivityKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string"></d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionOwnerKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">OwnershipNotFoundInExceptionOwnerSettings</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiOriginalExceptionKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Microsoft.Crm.Tools.ImportExportPublish.ImportGenericEntitiesException: CanvasApp import: FAILURE: No file with that name found ---&gt; Microsoft.Crm.Tools.ImportExportPublish.ImportGenericEntitiesException: CanvasApp import: FAILURE: No file with that name found ---&gt; Microsoft.Crm.CrmArgumentException: No file with that name found ---&gt; System.ArgumentException: No file with that name found
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Tools.ImportExportPublish.CrmUnzipFileSet.GetFileByName(String fileName, Int32&amp; fileSize)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportFileSetBase.LeaseBufferForFileAsByteArray(String fileName, Int32&amp; fileSize)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.&lt;UpdateAppBlobMappingForKey&gt;d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.&lt;UploadAppAssetsToContainerAndGetNewMapping&gt;d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.&lt;ImportAppToPowerAppsService&gt;d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportHandler.ImportInternal()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportHandler.&lt;Import&gt;b__36_0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.ImportAndUpdateProgress(ImportHandler ih)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.ProcessHandlers(String[] importEntities, Hashtable ht, String&amp; curPath, ImportHandler&amp; ihForCurrentPath, CounterList listCounters)
   at Microsoft.Crm.Tools.ImportExportPublish.RootImportHandler.RunImport(String[] importEntities)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImport(String[] importEntities)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImport()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RunImportInternal(Boolean withSolutionManifest)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.&lt;&gt;c__DisplayClass157_0.&lt;RunImport&gt;b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Crm.WebServices.ImportXmlService.ImportSolutionSkipCapableInternal(Boolean overwriteUnmanagedCustomizations, Boolean publishWorkflows, Byte[] customizationFile, Guid importJobId, Boolean convertToManaged, Boolean skipProductUpdateDependencies, Boolean holdingSolution, ExecutionContext context, Boolean skipQueueRibbonJob, LayerDesiredOrder layerDesiredOrder, Boolean asyncRibbonProcessing, EntityCollection componentParameters, Boolean isTemplateMode, String templateSuffix, SolutionParameters solutionParameters, String templateDisplayNamePrefix)
   at Microsoft.Crm.WebServices.ImportXmlService.ImportSolutionSkipCapable(Boolean overwriteUnmanagedCustomizations, Boolean publishWorkflows, Byte[] customizationFile, Guid importJobId, Boolean convertToManaged, Boolean skipProductUpdateDependencies, Boolean holdingSolution, ExecutionContext context, Boolean skipQueueRibbonJob, LayerDesiredOrder layerDesiredOrder, Boolean asyncRibbonProcessing, EntityCollection componentParameters, Boolean isTemplateMode, String templateSuffix, SolutionParameters solutionParameters, String templateDisplayNamePrefix)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.&lt;&gt;c__DisplayClass6_0.&lt;RunStep&gt;b__0()</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiStepKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/" i:type="d4p1:guid">1b830950-e106-4ee1-b3fd-d348cb65dc8d</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiDepthKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">2</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiActivityIdKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/" i:type="d4p1:guid">33d24da6-0092-4635-b302-67d485bf3ea2</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiPluginSolutionNameKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">System</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiStepSolutionNameKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">System</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionCategory</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">SystemFailure</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionMessageName</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">ImportGenericEntitiesError</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionHttpStatusCode</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">500</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>0</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Microsoft.Crm.CrmArgumentException: No file with that name found ---&gt; System.ArgumentException: No file with that name found
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Tools.ImportExportPublish.CrmUnzipFileSet.GetFileByName(String fileName, Int32&amp; fileSize)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportFileSetBase.LeaseBufferForFileAsByteArray(String fileName, Int32&amp; fileSize)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.&lt;UpdateAppBlobMappingForKey&gt;d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.&lt;UploadAppAssetsToContainerAndGetNewMapping&gt;d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.&lt;ImportAppToPowerAppsService&gt;d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>HasRetried</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">True</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>RetryExecutionStatus</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Microsoft.Crm.Core.Extensions.Retry.RetryExecutionStatus</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <HelpLink>http://go.microsoft.com/fwlink/?LinkID=398563&amp;error=Microsoft.Crm.CrmException%3a80048020&amp;client=platform</HelpLink>
  <Message>CanvasApp import: FAILURE: No file with that name found</Message>
  <Timestamp>2023-12-12T07:37:22.8713605Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>33d24da6-0092-4635-b302-67d485bf3ea2</ActivityId>
    <ErrorCode>-2147188704</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <HelpLink i:nil="true" />
    <Message>CanvasApp import: FAILURE: No file with that name found</Message>
    <Timestamp>2023-12-12T07:37:22.8713605Z</Timestamp>
    <ExceptionRetriable>false</ExceptionRetriable>
    <ExceptionSource i:nil="true" />
    <InnerFault>
      <ActivityId>33d24da6-0092-4635-b302-67d485bf3ea2</ActivityId>
      <ErrorCode>-2147220989</ErrorCode>
      <ErrorDetails xmlns:d4p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
      <HelpLink i:nil="true" />
      <Message>No file with that name found</Message>
      <Timestamp>2023-12-12T07:37:22.8713605Z</Timestamp>
      <ExceptionRetriable>false</ExceptionRetriable>
      <ExceptionSource i:nil="true" />
      <InnerFault>
        <ActivityId>33d24da6-0092-4635-b302-67d485bf3ea2</ActivityId>
        <ErrorCode>-2147220970</ErrorCode>
        <ErrorDetails xmlns:d5p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
        <HelpLink i:nil="true" />
        <Message>System.ArgumentException: No file with that name found</Message>
        <Timestamp>2023-12-12T07:37:22.8713605Z</Timestamp>
        <ExceptionRetriable>false</ExceptionRetriable>
        <ExceptionSource i:nil="true" />
        <InnerFault i:nil="true" />
        <OriginalException i:nil="true" />
        <TraceText i:nil="true" />
      </InnerFault>
      <OriginalException i:nil="true" />
      <TraceText i:nil="true" />
    </InnerFault>
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>
2023-12-12T07:37:24.6646966Z ##[section]Finishing: Import Patch to DVM
```[tasklist]
### Tasks
```

**Comment by SheikShaikShaVali** [comment]
I'm facing the exact same issue, this started just today. Any fix for this?

**Comment by marfilsKrul** [comment]
Me too. Any fix?

**Comment by marfilsKrul** [comment]
I've changed the version to V2 and it is working now
Check this - https://powerusers.microsoft.com/t5/Building-Power-Apps/Canvas-App-Release-Pipeline-Failing-with-Error-No-file-with-that/td-p/2504155

**Comment by phecke** [comment]
@rahulz55 We do not provide support here. If you are having trouble running one of our code samples, let us know.
